from PyQt5.QtWidgets import QWidget, QGridLayout,QVBoxLayout, QLabel,QSizePolicy
from PyQt5 import QtWidgets, QtCore, QtGui
class Page5(QWidget):
    def __init__(self):
        super().__init__()
        self.pg_settings = QtWidgets.QWidget()
        self.pg_settings.setObjectName("pg_settings")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pg_settings)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_19 = QtWidgets.QWidget(self.pg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setMinimumSize(QtCore.QSize(1390, 0))
        self.widget_19.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.widget_19.setProperty("class", "with_border")
        self.widget_19.setStyleSheet("QWidget {\n"
"    border-radius: 25px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_19.setObjectName("widget_19")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget_19)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(30, -1, -1, -1)
        self.formLayout_2.setHorizontalSpacing(11)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.widget_14 = QtWidgets.QWidget(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(500, 100))
        self.widget_14.setMaximumSize(QtCore.QSize(500, 100))
        self.widget_14.setObjectName("widget_14")
        self.formLayout = QtWidgets.QFormLayout(self.widget_14)
        self.formLayout.setContentsMargins(0, 20, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lb_welcome = QtWidgets.QLabel(self.widget_14)
        self.lb_welcome.setText("Вітаємо,")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_welcome.sizePolicy().hasHeightForWidth())
        self.lb_welcome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_welcome.setFont(font)
        self.lb_welcome.setObjectName("lb_welcome")
        self.horizontalLayout_8.addWidget(self.lb_welcome)
        self.lb_username = QtWidgets.QLabel(self.widget_14)
        self.lb_username.setText("Олена")
        self.lb_username.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_username.setFont(font)
        self.lb_username.setObjectName("lb_username")
        self.horizontalLayout_8.addWidget(self.lb_username)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_8)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.widget_14)
        self.lb_email = QtWidgets.QLabel(self.widget_19)
        self.lb_email.setText("Електронна адреса")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_email.sizePolicy().hasHeightForWidth())
        self.lb_email.setSizePolicy(sizePolicy)
        self.lb_email.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_email.setFont(font)
        self.lb_email.setObjectName("lb_email")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lb_email)
        self.le_email = QtWidgets.QLineEdit(self.widget_19)
        self.le_email.setPlaceholderText("qwerty@gmail.com")
        self.le_email.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_email.setFont(font)
        self.le_email.setInputMask("")
        self.le_email.setText("")
        self.le_email.setObjectName("le_email")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.le_email)
        self.btn_email = QtWidgets.QPushButton(self.widget_19)
        self.btn_email.setText("Оновити електронну адресу")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_email.sizePolicy().hasHeightForWidth())
        self.btn_email.setSizePolicy(sizePolicy)
        self.btn_email.setMinimumSize(QtCore.QSize(300, 50))
        self.btn_email.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_email.setFont(font)
        self.btn_email.setStyleSheet("border: 1px solid #C0C0C0; /* Рамка прогрес-бара */\n"
"border-radius:25px;       /* Згладжені кути */\n"
"background: #516ed9; /* Фон прогрес-бара */\n"
"text-align: center;        /* Текст посередині */\n"
"font: 75 15pt \"Bahnschrift\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_email.setObjectName("btn_email")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.btn_email)
        self.lb_password = QtWidgets.QLabel(self.widget_19)
        self.lb_password.setText("Змінити пароль")
        self.lb_password.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lb_password.setFont(font)
        self.lb_password.setObjectName("lb_password")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lb_password)
        self.le_password = QtWidgets.QLineEdit(self.widget_19)
        self.le_password.setPlaceholderText("Введи пароль")
        self.le_password.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_password.setFont(font)
        self.le_password.setObjectName("le_password")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.le_password)
        self.btn_password = QtWidgets.QPushButton(self.widget_19)
        self.btn_password.setText("Оновити пароль")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_password.sizePolicy().hasHeightForWidth())
        self.btn_password.setSizePolicy(sizePolicy)
        self.btn_password.setMinimumSize(QtCore.QSize(300, 50))
        self.btn_password.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_password.setFont(font)
        self.btn_password.setStyleSheet("border: 1px solid #C0C0C0; /* Рамка прогрес-бара */\n"
"border-radius:25px;       /* Згладжені кути */\n"
"background: #516ed9; /* Фон прогрес-бара */\n"
"text-align: center;        /* Текст посередині */\n"
"font: 75 15pt \"Bahnschrift\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_password.setObjectName("btn_password")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.btn_password)
        self.gridLayout_7.addWidget(self.widget_19, 1, 0, 1, 1)
        self.lb_settings = QtWidgets.QLabel(self.pg_settings)
        self.lb_settings.setText("Налаштування")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lb_settings.setFont(font)
        self.lb_settings.setObjectName("lb_settings")
        self.gridLayout_7.addWidget(self.lb_settings, 0, 0, 1, 1)
        self.setLayout(self.gridLayout_7)